name: Build Android

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build APK
    environment: Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          log-accepted-android-sdk-licenses: false

      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          version: "^11.20.0"
          install: false

      - name: Preapprove build scripts
        run: pnpm config set --local dangerouslyAllowAllBuilds true

      - name: Install standard dependencies
        run: pnpm ci

      - name: Install Android app dependencies
        run: pnpm add @capacitor/core @capacitor/cli @capacitor/android @capacitor/assets

      - name: Build project app
        run: pnpm run build

      - name: Add android folder
        run: pnpm exec cap add android

      - name: Generate icons and splash screen to android folder 
        run:  if [ -d "./resources" ]; then pnpm exec capacitor-assets generate --android; fi

      - name: Capacitor sync
        run: pnpm exec cap sync

      - name: Build app bundle
        run: cd android && ./gradlew --no-daemon assembleRelease

      - name: Align and Sign Build
        uses: kevin-david/zipalign-sign-android-release@v2
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: ./android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          zipAlign: true
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
        
      - name: release
        uses: softprops/action-gh-release@v3
        id: create_release
        with:
          files: ${{ steps.sign_app.outputs.signedReleaseFile }}